name: AncientBook
main: mccity.plugins.ancientbook.AncientBookPlugin
version: 1.7
description: Simple book manager
author: Galaran

commands:
    ancientbook:
        description: AncientBook main command
        aliases: [abook]

permissions:
    ancientbook.command:
        default: op