name: AncientBook
main: mccity.plugins.ancientbook.AncientBookPlugin
version: 1.5
description: Predefined books manager and BookWorm to 1.3 converter
author: Galaran

commands:
    ancientbook:
        description: AncientBook main command
        aliases: [abook]

permissions:
    ancientbook.command:
        default: op